import type { Metadata } from "next";
// import { Inter } from 'next/font/google'
import '@/styles/main.scss'


// const inter = Inter({ subsets: ['latin'], variable: '--font-primary' })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="it" data-theme="light"> {/* Cambia in "dark" per testare */}
      <body>{children}</body>
    </html>
  )
}